# Module 5 Assignment -- L Larkin
Due Saturday by 9am  Points 100  Submitting a website url
Do a correlation and regression of your assigned group dataset. This is an individual assignment!

In [50]:
import pandas as pd
import numpy as np

In [32]:
# LOAD NYC PROPERTY SALES AFTER MANUALLY SCRUBBING IT
Location = "datasets/datasets/nyc-rolling-sales-CLEAN-COR.csv"
df = pd.read_csv(Location)
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AT_PRESENT,BLOCK,LOT,EASEMENT,BUILDING_CLASS_AT_PRESENT,ADDRESS,APARTMENT_NUMBER,...,RESIDENTIAL_UNITS,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE
0,4,AIRPORT LA GUARDIA,01 ONE FAMILY DWELLINGS,1,976,15,,A5,21-20 81ST STREET,,...,1,0,1,1800,1224,1950,1,A5,792000,7/26/2017
1,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6360,157,,A5,36 BAY 10TH STREET,,...,1,0,1,1547,1428,1930,1,A5,800000,2/27/2017
2,2,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030,65,,A1,4455 PARK AVENUE,,...,1,0,1,1622,1587,1899,1,A1,140000,5/12/2017
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,,...,5,0,5,1633,6440,1900,2,C2,6625000,7/19/2017
4,5,ANNADALE,01 ONE FAMILY DWELLINGS,1,6205,22,,A5,83 EAGAN AVENUE,,...,1,0,1,1546,1579,1986,1,A5,437500,5/30/2017

In [33]:
df.shape

(28335, 21)

In [34]:
df.corr()

,BOROUGH,BLOCK,LOT,ZIP_CODE,RESIDENTIAL_UNITS,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,SALE_PRICE
BOROUGH,1.000000,0.162289,0.023759,0.083582,-0.104806,-0.011419,-0.091743,0.006015,-0.107125,0.337871,-0.235838,-0.102848
BLOCK,0.162289,1.000000,0.041649,0.510479,-0.055922,-0.006305,-0.049082,-0.005736,-0.064159,0.061933,-0.178191,-0.065594
LOT,0.023759,0.041649,1.000000,-0.086356,-0.009056,-0.004533,-0.009955,0.009193,-0.009230,0.104848,-0.040395,-0.010442
ZIP_CODE,0.083582,0.510479,-0.086356,1.000000,-0.062268,-0.003669,-0.052720,-0.022305,-0.076210,-0.236201,-0.101244,-0.065370
RESIDENTIAL_UNITS,-0.104806,-0.055922,-0.009056,-0.062268,1.000000,0.011844,0.820068,0.515109,0.719661,-0.002305,0.079689,0.138794
COMMERCIAL_UNITS,-0.011419,-0.006305,-0.004533,-0.003669,0.011844,1.000000,0.581931,0.061238,0.065627,0.001386,0.079003,0.047690
TOTAL_UNITS,-0.091743,-0.049082,-0.009955,-0.052720,0.820068,0.581931,1.000000,0.453986,0.622859,-0.001081,0.109865,0.140170
LAND_SQUARE_FEET,0.006015,-0.005736,0.009193,-0.022305,0.515109,0.061238,0.453986,1.000000,0.713403,0.027800,0.100833,0.044265
GROSS_SQUARE_FEET,-0.107125,-0.064159,-0.009230,-0.076210,0.719661,0.065627,0.622859,0.713403,1.000000,0.032444,0.197334,0.518733
YEAR_BUILT,0.337871,0.061933,0.104848,-0.236201,-0.002305,0.001386,-0.001081,0.027800,0.032444,1.000000,-0.020793,0.001324
TAX_CLASS_AT_TIME_OF_SALE,-0.235838,-0.178191,-0.040395,-0.101244,0.079689,0.079003,0.109865,0.100833,0.197334,-0.020793,1.000000,0.157311
SALE_PRICE,-0.102848,-0.065594,-0.010442,-0.065370,0.138794,0.047690,0.140170,0.044265,0.518733,0.001324,0.157311,1.000000

In [11]:
# The variables that have the greatest correlation (>= 0.5) are:
# ZIP CODE
# BLOCK
# TOTAL UNITS
# RESIDENTIAL UNITS
# COMMERCIAL UNITS
# LAND SQUARE FEET
# GROSS SQUARE FEET
# SALE PRICE

In [37]:
# PERFORM MULTIPLE LINEAR REGRESSION

result=smf.ols('SALE_PRICE ~ ZIP_CODE + BLOCK + TOTAL_UNITS + RESIDENTIAL_UNITS + COMMERCIAL_UNITS + LAND_SQUARE_FEET + GROSS_SQUARE_FEET', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             SALE_PRICE   R-squared:                       0.598
Model:                            OLS   Adj. R-squared:                  0.598
Method:                 Least Squares   F-statistic:                     6030.
Date:                Fri, 08 Mar 2019   Prob (F-statistic):               0.00
Time:                        15:44:23   Log-Likelihood:            -4.9950e+05
No. Observations:               28335   AIC:                         9.990e+05
Df Residuals:                   28327   BIC:                         9.991e+05
Df Model:                           7
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          3.031e+06    1.7e+06      1.785      0.074   -2.98e+05    6.36e+06
ZIP_CODE           -141.0690    159.149     -0.886      0.375    -453.008     170.870
BLOCK               -39.4295     20.063     -1.965      0.049     -78.753      -0.106
TOTAL_UNITS       -6.958e+05   8.86e+05     -0.785      0.432   -2.43e+06    1.04e+06
RESIDENTIAL_UNITS   2.83e+05   8.86e+05      0.319      0.749   -1.45e+06    2.02e+06
COMMERCIAL_UNITS   7.032e+05   8.86e+05      0.794      0.427   -1.03e+06    2.44e+06
LAND_SQUARE_FEET   -338.3367      2.756   -122.768      0.000    -343.738    -332.935
GROSS_SQUARE_FEET   678.5760      3.380    200.789      0.000     671.952     685.200
==============================================================================
Omnibus:                    83405.751   Durbin-Watson:                   1.896
Prob(Omnibus):                  0.000   Jarque-Bera (JB):      26386843665.801
Skew:                          40.849   Prob(JB):                         0.00
Kurtosis:                    4729.861   Cond. No.                     1.17e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.17e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
RESULT: The two variables affecting sale price the most are Land Square-Feet and Gross-Square-Feet